##===- lib/Makefile -------------*- Makefile -*-===##
#
#
##===----------------------------------------------------------------------===##

LEVEL = ..
LIBRARYNAME = LLVMInstCnt
LINK_LIBS_IN_SHARED = 1
SHARED_LIBRARY = 1

CXXFLAGS = "-std=c++11"

include $(LEVEL)/Makefile.common

